### ISSUE TITLE
Receive - Unexpected exception 'Error: Not enough answers for question.'

### ISSUE THREAD

**Issue by polomint82** [alexa/skill-sample-nodejs-trivia#25]
The only way I can get this working is if I comment out line 114:
//throw new Error('Invalid Game Length.');
The problem is that Alexa repeats the same question over and over again for obvious reasons.

However, If I leave the code as-is on GitHub then I get the following exception:
2017-09-22T05:44:43.032Z	216b5f3c-9f59-11e7-80a2-9fef957fab76	Unexpected exception 'Error: Invalid Game Length.':
Error: Invalid Game Length.
at populateGameQuestions (/var/task/index.js:114:15)
at Object.StartGame (/var/task/index.js:242:31)
at emitOne (events.js:96:13)
at AlexaRequestEmitter.emit (events.js:188:7)
at AlexaRequestEmitter.EmitWithState (/var/task/node_modules/alexa-sdk/lib/alexa.js:296:15)
at Object.LaunchRequest (/var/task/index.js:91:14)
at emitNone (events.js:86:13)
at AlexaRequestEmitter.emit (events.js:185:7)
at AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:211:10)
at AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:176:23)

Would appreciate thoughts on what the issue might be. Doesn't seem like it's a big deal, but I did notice another user had added some quick fix to "const questions = proto_questions..." which did seem to indicate there is a problem with the question.js file.

**Comment by AlexaforMuggles** [comment]
Hi. I know it's kind of late but did you figure out how to solve the "Not enough answers for question." issue? I have the same issue. Number of answers in ANSWER_COUNT is correct and also didn't change from the template.

**Comment by harshsahu97** [comment]
Hey there! I'm getting the same error too.

**Comment by raisonhentry** [comment]
pls help issues

**Comment by akersh-s** [comment]
It's either been fixed in our latest update, or this is user error. if you're still having issues, try opening a post in our forums: https://forums.developer.amazon.com/ thanks
